### ISSUE TITLE
Question regarding the App Transport Security plist entry

### ISSUE THREAD

**Issue by roberto-robles** [iHealthLabs/IOS-SDK#3]
Why did this become a requirement?

**Comment by jzhw0130** [comment]
Sorry, the problem of the server.
Server update , Do not need now.

**Comment by Gorcyn** [comment]
_iOS comment — not specific to this SDK_

iOS 9.0 and OS X v10.11 introduced a new feature: Unsecured HTTP requests are no longer allowed by the system. Your applications must now define this option to allow them afresh.

You can check documentation about this new NSAppTransportSecurity feature [here](https://developer.apple.com/library/prerelease/ios/documentation/General/Reference/InfoPlistKeyReference/Articles/CocoaKeys.html#//apple_ref/doc/uid/TP40009251-SW33)

**Comment by jzhw0130** [comment]
Do not need now.
Thanks
