### ISSUE TITLE
Device detection and entitlements issues since iOS 10

### ISSUE THREAD

**Issue by sbstcano** [iHealthLabs/IOS-SDK#8]
Hi,

Since iOS 10, my iHealth devices encounter intermittent detection issues. And, at times, give the following error :

> Couldn't find the "com.apple.private.externalaccessory.showallaccessories" entitlement

I'm using an iPad Air 2 fyi.

**Comment by wushuang2012** [comment]
@sbstcano  You can refer to this link：   https://forums.developer.apple.com/thread/61646.  Even if the error message, the SDK is also can be used normally.
