### ISSUE TITLE
UserAuthen_UserInvalidateRight

### ISSUE THREAD

**Issue by hrabkin** [iHealthLabs/IOS-SDK#9]
We have integrated SDK for BP5 and HS4 devices with registered credentials, they work fine. But when I had tried these credentials in the sample app which delivered with SDK for BG5 device I received an error at authorization step: UserAuthen_UserInvalidateRight - "User hasn't been authorized"

My clientID, clientSecret, userID are valid ones. Why I see that error ?

**Comment by jzhw0130** [comment]
@Zestu 

Hi 

Could you send me your clientID  clientSecret userID?
Email: jingzhiwei@ihealthlabs.com.cn

We will check the problem.

Jing

**Comment by hrabkin** [comment]
Has solved, can be closed
